version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    logging:
      driver: none
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=demo
  dbt:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - .:/app
  